export const t = {
    "private": null, "password": false, "access": false, "readOnly": false, "payload": {
        "tree": [
            {
                "name": "Main page",
                "childIds": ["905zwc1g7dv", "s9wqgi3x8fg", "zp5atscv8w"],
                "hours": 0,
                "parentId": null,
                "childIndex": 0,
                "image": null,
                "variant": "default",
                "group": 0,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "a9k3nae0l5"
            },
            {
                "name": "",
                "childIds": [],
                "hours": 0,
                "parentId": "a9k3nae0l5",
                "childIndex": 0,
                "image": null,
                "variant": "default",
                "group": 0,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "905zwc1g7dv"
            },
            {
                "name": "",
                "childIds": [],
                "hours": 0,
                "parentId": "a9k3nae0l5",
                "childIndex": 1,
                "image": null,
                "variant": "default",
                "group": 0,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "s9wqgi3x8fg"
            },
            {
                "name": "",
                "childIds": [],
                "hours": 0,
                "parentId": "a9k3nae0l5",
                "childIndex": 2,
                "image": null,
                "variant": "default",
                "group": 0,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "zp5atscv8w"
            },
            {
                "name": "Cookies",
                "childIds": [],
                "hours": 0,
                "parentId": null,
                "childIndex": 0,
                "image": null,
                "variant": "default",
                "group": 1,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "tjut1qy17fd"
            },
            {
                "name": "404 error",
                "childIds": [],
                "hours": 0,
                "parentId": null,
                "childIndex": 1,
                "image": null,
                "variant": "default",
                "group": 1,
                "comments": 0,
                "color": "blue",
                "isCollapsed": false,
                "notes": { "enabledTypes": ["note", "seo"], "fields": { "note": { "type": "note", "value": "" } } },
                "url": "",
                "id": "blvf44eorqs"
            }
        ],
        "lineItems": [
            {
                "name": "Design",
                "hours": 0,
                "rate": 4500,
                "isDefault": true,
                "isEstimate": true,
                "color": 1,
                "factor": false,
                "id": "yvbk8cgfafr",
                "childIndex": 0
            }, {
                "name": "Frontend",
                "hours": 0,
                "rate": 0,
                "isDefault": false,
                "isEstimate": true,
                "color": 2,
                "factor": false,
                "id": "l41itcxmyb",
                "childIndex": 1
            }, {
                "name": "Development",
                "hours": 0,
                "rate": 0,
                "isDefault": false,
                "isEstimate": true,
                "color": 3,
                "factor": false,
                "id": "u791lxbe6k",
                "childIndex": 2
            }, {
                "name": "Testing",
                "hours": 0,
                "rate": 0,
                "isDefault": false,
                "isEstimate": false,
                "color": 0,
                "factor": false,
                "id": "r61kja39fyc",
                "childIndex": 3
            }, {
                "name": "Project management",
                "hours": 0,
                "rate": 0,
                "isDefault": false,
                "isEstimate": false,
                "color": 0,
                "factor": false,
                "id": "a1jd4snffj7",
                "childIndex": 4
            }],
        "blocks": [
            {
                "name": "Header",
                "body": "",
                "color": "topaz",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "nodeId": "a9k3nae0l5",
                "id": "2arb8oiqmep",
                "childIndex": 0
            }, {
                "name": "Introduction",
                "body": "",
                "color": "blue",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "nodeId": "a9k3nae0l5",
                "id": "mhhppja4a7",
                "childIndex": 1
            }, {
                "name": "Services",
                "body": "",
                "color": "blue",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "nodeId": "a9k3nae0l5",
                "id": "svzsfvsulz",
                "childIndex": 2
            }, {
                "name": "Latest news",
                "body": "",
                "color": "blue",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "nodeId": "a9k3nae0l5",
                "id": "42oz35natfn",
                "childIndex": 3
            }, {
                "name": "Footer",
                "body": "",
                "color": "purple",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "nodeId": "a9k3nae0l5",
                "id": "p604epgt9f",
                "childIndex": 4
            }, {
                "name": "",
                "body": "",
                "color": "blue",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "id": "ogqm7vapefn",
                "nodeId": "s9wqgi3x8fg",
                "childIndex": 0
            }, {
                "name": "",
                "body": "",
                "color": "blue",
                "wireframe": "",
                "isSymbol": false,
                "symbolId": null,
                "user": "",
                "id": "2bvql35ekr8",
                "nodeId": "zp5atscv8w",
                "childIndex": 0
            }],
        "arrows": [],
        "stickyNotes": [],
        "symbols": [],
        "symbolsLibrary": [],
        "project": {
            "team": null,
            "members": [{
                "id": "7a5c55e3-6eb4-4014-91c9-506509fa5319",
                "fullName": "Naveed ul Hassan",
                "emailAddress": "08es34@gmail.com",
                "color": "orange",
                "pending": false,
                "portable": false
            }],
            "name": "Octopus",
            "vat": 20,
            "currency": "USD",
            "legend": true,
            "legendItems": [],
            "images": false,
            "estimate": false,
            "privateEstimate": false,
            "mobile": false,
            "theme": "light",
            "customColors": [],
            "tree": "map",
            "template": false,
            "blockColor": "blue",
            "treeColor": "blue",
            "sections": { "m3n8qhovvdi": { "id": "m3n8qhovvdi", "name": "SECTION", "order": 1 } },
            "createdNoteId": null,
            "readOnlyComments": true,
            "commentReactions": [],
            "blockReactions": [],
            "subscribers": ["7a5c55e3-6eb4-4014-91c9-506509fa5319"],
            "id": "rkb3kg8n4w9",
            "readOnlyId": "2czei3ajyhs",
            "createdAt": 1663776233,
            "updatedAt": 1663840306,
            "expired": false,
            "exportable": false,
            "advanced": false,
            "archived": false,
            "legacy": false,
            "ownerId": "7a5c55e3-6eb4-4014-91c9-506509fa5319",
            "public": true,
            "avatars": [],
            "avatar": null,
            "customAvatar": null,
            "integrations": { "figma": false },
            "ownerPlan": "plan_free",
            "hasPassword": false
        },
        "comments": []
    }
}
